services:
  redisserver:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      backend:
        aliases:
          - "redis"
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "copier_bot"
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  core:
    image: botcore:v1
    build:
      context: ./bot-artifacts/bot-core
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: 7126426046:AAGEmRKG4TB4YXBkbWWds4F76Y6ECeW3j5c
    depends_on:
      database:
        condition: service_healthy
      redisserver:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
